### PR TITLE
Add type hint Optional

### PR DESCRIPTION
**Pull request by jwhonce**
* Add type hint Optional to the ETAPI methods
* Let black abuse the client.py file

### CODE REVIEW

**Comment by jwhonce** [comment]
Some questions:
1) Is tox configured to "work"? I get errors 
```
py36: commands[0]> check-manifest --ignore 'tox.ini,tests/**'
lists of files in version control and sdist do not match!
missing from VCS:
  MANIFEST.in
no MANIFEST.in found
py36: exit 1 (9.82 seconds) /home/jhonce/Projects/Python/trilium-py> check-manifest --ignore 'tox.ini,tests/**' pid=417968
py36: FAIL ✖ in 12.64 seconds
```
2) Do you have a strong opinion on Black's formatting changes? If so, please let me know and I will add a configuration to tone it down as needed.
3) I am unfamiliar with `from sample.simple import add_one`, what package would I need to install to pick that up? Or is this a placeholder for something else.

**Comment by Nriver** [comment]
1. I think that file comes from certain python package template project. I never used it.
2. The formatting looks good. But I prefer to use single quote over double quotes. I am unfamiliar with `Black`, is it possible to make it to single quote?
3. It's the same as 1.

**Comment by jwhonce** [comment]
@Nriver I setup `pyproject.toml` to leave the quotes alone.

**Comment by Nriver** [comment]
Thank you!

**Pull request merged**
